name: paperwocode
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - scikit-learn>=1.3.0
  - pytorch
  - torchvision
  - torchaudio
  - pyyaml>=6.0
  - tqdm>=4.65.0
  - seaborn>=0.12.0
  - pip:
    - 'markitdown[all]~=0.1.0a1'
    - anthropic>=0.8.0
    - openai>=1.3.0
    - PyPDF2>=3.0.0
    - tiktoken>=0.5.0
